# These are supported funding model platforms

github: # Gottem87, VS-Code
open_collective: # Gottem87
liberapay: # Gottem87
issuehunt: # Gottem87
otechie: # Gottem87
lfx_crowdfunding: # VS-Code
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
